name: time_picker_spinner_pop_up
description: A package show popup anchor for pick date time by using spinner cupertino style
version: 2.0.0
homepage: https://github.com/tuannvm2109/time_picker_spinner_pop_up

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
